services:
  backup:
    image: ghcr.io/alcelafranque/alcelafranque/postgres-backup-s3:16
    volumes:
      - /usr/local/share/ca-certificates/cloud-init-ca-cert-1.crt:/ca.crt:ro
    environment:
      SCHEDULE: '@midnight'
      BACKUP_KEEP_DAYS: 30
      PASSPHRASE: passphrase
      S3_ENDPOINT: https://s3.random-s3-provider.com
      AWS_ACCESS_KEY_ID: acces-key
      AWS_SECRET_ACCESS_KEY: secret-key
      S3_BUCKET: bucket
      S3_PREFIX: db1-fra-par1
      S3_REGION: paris
      POSTGRES_HOST: psql-ro.svc.cluster.local
      POSTGRES_DATABASE: database
      POSTGRES_USER: dumper-01
      POSTGRES_PASSWORD: mypassword
      AWS_CA_BUNDLE: ca.crt
